<?php
/* La liste des mots kills.
 * Il doit y avoir asser de mot kills car on utilise 2 par semaines.
 * il doit donc y avoir 52 *2 = 104. mot kill ici.
 * 
 * Sur le vrais habboshoot, j'en ai mis 130, histoire d'avoir de la marge :-))
 * 
 */

$motkillall = '*PAN.hbsh.fr*
*ZEK.hbsh.fr*
*DAM.hbsh.fr*
*GLOK.hbsh.fr*
*LEP.hbsh.fr*
*TAK.hbsh.fr*
*CLAC.hbsh.fr*
*SHOOT.hbsh.fr*
*PONG.hbsh.fr*
*ATAK.hbsh.fr*
*KEF.hbsh.fr*
*PIF.hbsh.fr*
*GLAK.hbsh.fr*
*POF.hbsh.fr*
*ATIC.hbsh.fr*
*TOK.hbsh.fr*
*TOK.hbsh.fr*
*ATAC.hbsh.fr*
*CLOC.hbsh.fr*
*DAM.hbsh.fr*
*BAF.hbsh.fr*
*CLOC.hbsh.fr*
*ATAK.hbsh.fr*
*BONG.hbsh.fr*
*BING.hbsh.fr*
*ATOC.hbsh.fr*
*KAF.hbsh.fr*
*POF.hbsh.fr*
*KOF.hbsh.fr*
*ZEK.hbsh.fr*
*PAUF.hbsh.fr*
*BANG.hbsh.fr*
*KOF.hbsh.fr*
*GAK.hbsh.fr*
*CLAC.hbsh.fr*
*BING.hbsh.fr*
*KIF.hbsh.fr*
*BOUF.hbsh.fr*
*ZAK.hbsh.fr*
*GOK.hbsh.fr*
*PROF.hbsh.fr*
*PEF.hbsh.fr*
*KAK.hbsh.fr*
*GOK.hbsh.fr*
*PAN.hbsh.fr*
*PROF.hbsh.fr*
*BANG.hbsh.fr*
*GAK.hbsh.fr*
*ZAK.hbsh.fr*
*ATAC.hbsh.fr*
*KLAK.hbsh.fr*
*BOUM.hbsh.fr*
*KLEK.hbsh.fr*
*TAM.hbsh.fr*
*FIOU.hbsh.fr*
*PAUF.hbsh.fr*
*GUK.hbsh.fr*
*ZOK.hbsh.fr*
*BIF.hbsh.fr*
*KAF.hbsh.fr*
*PEM.hbsh.fr*
*PAF.hbsh.fr*
*PONG.hbsh.fr*
*CRAC.hbsh.fr*
*PAK.hbsh.fr*
*GLOK.hbsh.fr*
*PAM.hbsh.fr*
*FIOU.hbsh.fr*
*GIK.hbsh.fr*
*CRAC.hbsh.fr*
*DOM.hbsh.fr*
*POUF.hbsh.fr*
*KLAK.hbsh.fr*
*PEF.hbsh.fr*
*FOF.hbsh.fr*
*GLAK.hbsh.fr*
*PIF.hbsh.fr*
*BOF.hbsh.fr*
*KLOK.hbsh.fr*
*ATOC.hbsh.fr*
*PIM.hbsh.fr*
*BIF.hbsh.fr*
*PIM.hbsh.fr*
*SHOOT.hbsh.fr*
*BING.hbsh.fr*
*BING.hbsh.fr*
*BOUM.hbsh.fr*
*DOM.hbsh.fr*
*FOF.hbsh.fr*
*POUF.hbsh.fr*
*TAK.hbsh.fr*
*KLOK.hbsh.fr*
*BAF.hbsh.fr*
*POUF.hbsh.fr*
*BIM.hbsh.fr*
*BAM.hbsh.fr*
*KIF.hbsh.fr*
*GIK.hbsh.fr*
*ZOK.hbsh.fr*
*POUF.hbsh.fr*
*BOM.hbsh.fr*
*POM.hbsh.fr*
*BOM.hbsh.fr*
*KEF.hbsh.fr*
*KLEK.hbsh.fr*
*TAM.hbsh.fr*
*POM.hbsh.fr*
*BIM.hbsh.fr*
*PAK.hbsh.fr*
*PAF.hbsh.fr*
*BONG.hbsh.fr*
*BAM.hbsh.fr*
*BOUF.hbsh.fr*
*PAM.hbsh.fr*
*LEP.hbsh.fr*
*GUK.hbsh.fr*
*KAK.hbsh.fr*
*BOF.hbsh.fr*
*ATIC.hbsh.fr*
*PEM.hbsh.fr*';
?>
